ignore:
    - "**/Add_Profile_Pic.java"
    - "**/Display_Posts.java"
    - "**/Forgot_Password.java"
    - "**/fragment_followers.java"
    - "**/fragment_following.java"
    - "**/Fragment_PostFeed.java"
    - "**/Generated.java"
    - "**/Main_Activity.java"
    - "**/PagerAdapter.java"
    - "**/Search_User_class.java"
    - "**/Show_Profile_Details.java"
    - "**/Sign_Up.java"
    - "**/user_display.java"
    - "**/FcmNotificationsSender.java"
    - "**/Push_Notification_Service.java"
    - "**/Replies.java"
