ignore:
    - "**/Add_Profile_Pic"
    - "**/Display_Posts"
    - "**/Forgot_Password"
    - "**/fragment_followers"
    - "**/fragment_followering"
    - "**/Fragment_PostFeed"
    - "**/Generated"
    - "**/Main_Activity"
    - "**/PagerAdapter"
    - "**/Search_User_class"
    - "**/Show_Profile_Details"
    - "**/Sign_Up"
    - "**/user_display"